apiVersion: v1
kind: Service
metadata:
  name: metadata-grpc-service
  namespace: kubeflow
spec:
  ports:
    - port: 8080
      targetPort: 8080
  clusterIP: None

---
apiVersion: v1
kind: Endpoints
metadata:
  name: metadata-grpc-service
  namespace: kubeflow
subsets:
  - addresses:
      - ip: 10.10.10.73
    ports:
      - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: kubeflow
spec:
  ports:
    - port: 9000
      targetPort: 9000
  clusterIP: None

---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-service
  namespace: kubeflow
subsets:
  - addresses:
      - ip: 10.10.10.72
    ports:
      - port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kubeflow
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None

---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: kubeflow
subsets:
  - addresses:
      - ip: 10.10.10.74
    ports:
      - port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: metadata-envoy-service
  namespace: kubeflow
spec:
  ports:
    - port: 9090
      targetPort: 9090
  clusterIP: None
  
---
apiVersion: v1
kind: Endpoints
metadata:
  name: metadata-envoy-service
  namespace: kubeflow
subsets:
  - addresses:
      - ip: 10.10.10.75
    ports:
      - port: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: kubeflow
spec:
  ports:
    - port: 443
      targetPort: 443
  clusterIP: None
  
---
apiVersion: v1
kind: Endpoints
metadata:
  name: controller-manager-service
  namespace: kubeflow
subsets:
  - addresses:
      - ip: 10.10.10.76
    ports:
      - port: 443