apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"mysql","application-crd-id":"kubeflow-pipelines"},"name":"mysql","namespace":"kubeflow"},"spec":{"selector":{"matchLabels":{"app":"mysql","application-crd-id":"kubeflow-pipelines"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"mysql","application-crd-id":"kubeflow-pipelines"}},"spec":{"containers":[{"args":["--datadir","/var/lib/mysql","--default-authentication-plugin=mysql_native_password","--disable-log-bin"],"env":[{"name":"MYSQL_ALLOW_EMPTY_PASSWORD","value":"true"}],"image":"gcr.io/ml-pipeline/mysql:8.0.26","name":"mysql","ports":[{"containerPort":3306,"name":"mysql"}],"resources":{"requests":{"cpu":"100m","memory":"800Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"runAsGroup":0,"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}},"volumeMounts":[{"mountPath":"/var/lib/mysql","name":"mysql-persistent-storage"}]}],"serviceAccountName":"mysql","volumes":[{"name":"mysql-persistent-storage","persistentVolumeClaim":{"claimName":"mysql-pv-claim"}}]}}}}
  
  generation: 3
  labels:
    app: mysql
    application-crd-id: kubeflow-pipelines
  name: mysql
  namespace: kubeflow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql
      application-crd-id: kubeflow-pipelines
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        application-crd-id: kubeflow-pipelines
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - args:
        - --datadir
        - /var/lib/mysql
        - --default-authentication-plugin=mysql_native_password
        - --disable-log-bin
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        image: gcr.io/ml-pipeline/mysql:8.0.26
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 800Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 999
          runAsNonRoot: true
          runAsUser: 999
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: mysql
      serviceAccountName: mysql
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
